# Generated by Django 2.2 on 2019-04-02 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000, verbose_name='Content of comment')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('movie_type', models.CharField(max_length=10, verbose_name='Type')),
                ('year_of_release', models.IntegerField(verbose_name='Year')),
                ('data_type', models.CharField(max_length=4, verbose_name='Data type')),
                ('page', models.IntegerField(verbose_name='Page')),
                ('callback', models.CharField(max_length=100, verbose_name='JSONP callback name')),
                ('version', models.CharField(max_length=10, verbose_name='API version')),
                ('rank', models.IntegerField(verbose_name='Rank')),
                ('comments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Comments', verbose_name='Commnets')),
            ],
        ),
    ]
