# Generated by Django 2.2 on 2019-04-03 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190403_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imdbRating',
            field=models.CharField(max_length=15, verbose_name='imdbRating'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdbVotes',
            field=models.CharField(max_length=15, verbose_name='imdbVotes'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='metascore',
            field=models.CharField(max_length=15, verbose_name='Metascore'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year_of_release',
            field=models.CharField(max_length=4, verbose_name='Year'),
        ),
    ]
